# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  paths:
    include:
      - packages/order-experience-api
      - packages/order-backend
      - packages/core
      - packages/cart-backend
    exclude:
      - packages/order-experience-api/test/integration/order-experience-api.postman_collection.json
  tags:
    include:
      - order-experience-api/*
  branches:
    include:
      - master


# By default, use self-hosted agents
pool: Default

# Opting out of pull request validation
pr: none

resources:
  repositories:
    # Azure DevOps repository
    - repository: talpa-verkkokauppa-pipelines
      type: git
      # project/repository
      name: talpa-verkkokauppa/talpa-verkkokauppa-pipelines

extends:
  template: azure-pipelines-talpa-verkkokauppa-order-experience-api.yml@talpa-verkkokauppa-pipelines