version: '3.7'

services:
  product-experience-api:
    build:
      context: ./
      dockerfile: packages/product-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/product-experience-api/:/opt/app-root/src/packages/product-experience-api/
      - ./packages/product-experience-api/src/openapi.yaml:/opt/app-root/src/packages/product-experience-api/dist/openapi.yaml
      - ./packages/product-experience-api/nodemon.json:/opt/app-root/src/packages/product-experience-api/nodemon.json
      - ./packages/product-backend/:/opt/app-root/src/packages/product-backend/
      - ./packages/product-mapping-backend/:/opt/app-root/src/packages/product-mapping-backend/
      - ./packages/configuration-backend/:/opt/app-root/src/packages/configuration-backend/
      - ./packages/price-backend/:/opt/app-root/src/packages/price-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
    container_name: product-experience-api
    expose:
      - '8080'
    ports:
      - '8081:8080'
    command: yarn workspace @verkkokauppa/product-experience-api dev
    environment:
      - SERVICE_NAME=product-experience-api
    env_file:
      - .env.docker
    networks:
      - common
  price-experience-api:
    build:
      context: ./
      dockerfile: packages/price-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/price-experience-api/:/opt/app-root/src/packages/price-experience-api/
      - ./packages/price-experience-api/src/openapi.yaml:/opt/app-root/src/packages/price-experience-api/dist/openapi.yaml
      - ./packages/price-experience-api/nodemon.json:/opt/app-root/src/packages/price-experience-api/nodemon.json
      - ./packages/price-backend/:/opt/app-root/src/packages/price-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
    container_name: price-experience-api
    expose:
      - '8080'
    ports:
      - '8082:8080'
    command: yarn workspace @verkkokauppa/price-experience-api dev
    environment:
      - SERVICE_NAME=price-experience-api
    env_file:
      - .env.docker
    networks:
      - common
  cart-experience-api:
    build:
      context: ./
      dockerfile: packages/cart-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/cart-experience-api/:/opt/app-root/src/packages/cart-experience-api/
      - ./packages/cart-experience-api/nodemon.json:/opt/app-root/src/packages/cart-experience-api/nodemon.json
      - ./packages/cart-backend/:/opt/app-root/src/packages/cart-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
      - ./packages/product-backend/:/opt/app-root/src/packages/product-backend/
      - ./packages/price-backend/:/opt/app-root/src/packages/price-backend/
    container_name: cart-experience-api
    expose:
      - '8080'
    ports:
      - '8083:8080'
    command: yarn workspace @verkkokauppa/cart-experience-api dev
    environment:
      - SERVICE_NAME=cart-experience-api
    env_file:
      - .env.docker
    networks:
      - common
  order-experience-api:
    build:
      context: ./
      dockerfile: packages/order-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/order-experience-api/:/opt/app-root/src/packages/order-experience-api/
      - ./packages/order-experience-api/src/openapi.yaml:/opt/app-root/src/packages/order-experience-api/dist/openapi.yaml
      - ./packages/order-experience-api/nodemon.json:/opt/app-root/src/packages/order-experience-api/nodemon.json
      - ./packages/order-backend/:/opt/app-root/src/packages/order-backend/
      - ./packages/cart-backend/:/opt/app-root/src/packages/cart-backend/
      - ./packages/message-backend/:/opt/app-root/src/packages/message-backend/
      - ./packages/payment-backend/:/opt/app-root/src/packages/payment-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
      - ./packages/product-backend/:/opt/app-root/src/packages/product-backend/
      - ./packages/price-backend/:/opt/app-root/src/packages/price-backend/
      - ./packages/configuration-backend/:/opt/app-root/src/packages/configuration-backend/
    container_name: order-experience-api
    expose:
      - '8080'
    ports:
      - '8084:8080'
      - '9230:9229'
    command: yarn workspace @verkkokauppa/order-experience-api dev
    environment:
      - SERVICE_NAME=order-experience-api
    env_file:
      - .env.docker
    networks:
      - common
  payment-experience-api:
    build:
      context: ./
      dockerfile: packages/payment-experience-api/Dockerfile
      target: base
      args:
        - TZ=Europe/Helsinki
    volumes:
      - ./packages/payment-experience-api/:/opt/app-root/src/packages/payment-experience-api/
      - ./packages/payment-experience-api/src/openapi.yaml:/opt/app-root/src/packages/payment-experience-api/dist/openapi.yaml
      - ./packages/order-backend/:/opt/app-root/src/packages/order-backend/
      - ./packages/payment-backend/:/opt/app-root/src/packages/payment-backend/
      - ./packages/product-backend/:/opt/app-root/src/packages/product-backend/
      - ./packages/configuration-backend/:/opt/app-root/src/packages/configuration-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
      - ./packages/message-backend/:/opt/app-root/src/packages/message-backend/
    container_name: payment-experience-api
    expose:
      - '8080'
      - '8081'
    ports:
      - '8085:8080'
      - '8285:8081'
      - '9229:9229'
    command: yarn workspace @verkkokauppa/payment-experience-api dev
    environment:
      - SERVICE_NAME=payment-experience-api
      - VISMA_PAY_PRIVATE_KEY=MOCKKEY
      - VISMA_PAY_API_KEY=MOCKKEY
    env_file:
      - .env.docker
    networks:
      - common
  merchant-experience-api:
    build:
      context: ./
      dockerfile: packages/merchant-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/merchant-experience-api/:/opt/app-root/src/packages/merchant-experience-api/
      - ./packages/merchant-experience-api/src/openapi.yaml:/opt/app-root/src/packages/merchant-experience-api/dist/openapi.yaml
      - ./packages/merchant-experience-api/nodemon.json:/opt/app-root/src/packages/merchant-experience-api/nodemon.json
      - ./packages/configuration-backend/:/opt/app-root/src/packages/configuration-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
    container_name: merchant-experience-api
    expose:
      - '8080'
    ports:
      - '8086:8080'
      - '9231:9229'
    command: yarn workspace @verkkokauppa/merchant-experience-api dev
    environment:
      - SERVICE_NAME=merchant-experience-api
    env_file:
      - .env.docker
    networks:
      - common

  monitoring-experience-api:
    build:
      context: ./
      dockerfile: packages/monitoring-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/monitoring-experience-api/:/opt/app-root/src/packages/monitoring-experience-api/
      - ./packages/monitoring-experience-api/src/openapi.yaml:/opt/app-root/src/packages/monitoring-experience-api/dist/openapi.yaml
      - ./packages/monitoring-experience-api/nodemon.json:/opt/app-root/src/packages/monitoring-experience-api/nodemon.json
      - ./packages/configuration-backend/:/opt/app-root/src/packages/configuration-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
    container_name: monitoring-experience-api
    expose:
      - '8080'
    ports:
      - '8087:8080'
      - '9232:9229'
    command: yarn workspace @verkkokauppa/monitoring-experience-api dev
    environment:
      - SERVICE_NAME=monitoring-experience-api
    env_file:
      - .env.docker
    networks:
      - common

  hotreloader:
    build:
      context: ./
      dockerfile: packages/core/Dockerfile
      target: base
      args:
        - TZ=Europe/Helsinki
    volumes:
      - ./packages/auth-helsinki-profile/:/opt/app-root/src/packages/auth-helsinki-profile
      - ./packages/core/:/opt/app-root/src/packages/core
      - ./packages/cart-backend/:/opt/app-root/src/packages/cart-backend
      - ./packages/configuration-backend/:/opt/app-root/src/packages/configuration-backend
      - ./packages/message-backend/:/opt/app-root/src/packages/message-backend
      - ./packages/order-backend/:/opt/app-root/src/packages/order-backend
      - ./packages/payment-backend/:/opt/app-root/src/packages/payment-backend
      - ./packages/price-backend/:/opt/app-root/src/packages/price-backend
      - ./packages/product-backend/:/opt/app-root/src/packages/product-backend
      - ./packages/product-mapping-backend/:/opt/app-root/src/packages/product-mapping-backend
    container_name: hotreloader
#    command: yarn workspace @verkkokauppa/payment-experience-api dev
    env_file:
      - .env.docker
    networks:
      - common

networks:
  common:
