version: '3.7'

services:
  product-experience-api:
    build:
      context: ./
      dockerfile: packages/product-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/product-experience-api/:/opt/app-root/src/packages/product-experience-api/
      - ./packages/product-experience-api/nodemon.json:/opt/app-root/src/packages/product-experience-api/nodemon.json
      - ./packages/product-backend/:/opt/app-root/src/packages/product-backend/
      - ./packages/product-mapping-backend/:/opt/app-root/src/packages/product-mapping-backend/
      - ./packages/price-backend/:/opt/app-root/src/packages/price-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
    container_name: product-experience-api
    expose:
      - '8080'
    ports:
      - '8081:8080'
    command: yarn workspace @verkkokauppa/product-experience-api dev
    environment:
      - SERVICE_NAME=product-experience-api
      - PRODUCT_BACKEND_URL=https://ff102df2-94c3-4243-a4a1-6e449f78c633.mock.pstmn.io
      - PRODUCT_MAPPING_BACKEND_URL=https://9678a076-6612-441d-8970-30ddbc8a84da.mock.pstmn.io
      - PRICE_BACKEND_URL=https://3d615742-ed93-4415-8972-76c7103c5000.mock.pstmn.io
  price-experience-api:
    build:
      context: ./
      dockerfile: packages/price-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/price-experience-api/:/opt/app-root/src/packages/price-experience-api/
      - ./packages/price-experience-api/nodemon.json:/opt/app-root/src/packages/price-experience-api/nodemon.json
      - ./packages/price-backend/:/opt/app-root/src/packages/price-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
    container_name: price-experience-api
    expose:
      - '8080'
    ports:
      - '8082:8080'
    command: yarn workspace @verkkokauppa/price-experience-api dev
    environment:
      - SERVICE_NAME=price-experience-api
      - PRICE_BACKEND_URL=https://3d615742-ed93-4415-8972-76c7103c5000.mock.pstmn.io
  cart-experience-api:
    build:
      context: ./
      dockerfile: packages/cart-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/cart-experience-api/:/opt/app-root/src/packages/cart-experience-api/
      - ./packages/cart-experience-api/nodemon.json:/opt/app-root/src/packages/cart-experience-api/nodemon.json
      - ./packages/cart-backend/:/opt/app-root/src/packages/cart-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
      - ./packages/product-backend/:/opt/app-root/src/packages/product-backend/
      - ./packages/price-backend/:/opt/app-root/src/packages/price-backend/
    container_name: cart-experience-api
    expose:
      - '8080'
    ports:
      - '8083:8080'
      - '9229:9229'
    command: yarn workspace @verkkokauppa/cart-experience-api dev
    environment:
      - SERVICE_NAME=cart-experience-api
      - CART_BACKEND_URL=https://d526e9ec-74bf-4314-b708-f759a9d46958.mock.pstmn.io
      - PRICE_BACKEND_URL=https://3d615742-ed93-4415-8972-76c7103c5000.mock.pstmn.io
      - PRODUCT_BACKEND_URL=https://ff102df2-94c3-4243-a4a1-6e449f78c633.mock.pstmn.io
  order-experience-api:
    build:
      context: ./
      dockerfile: packages/order-experience-api/Dockerfile
      target: base
    volumes:
      - ./packages/order-experience-api/:/opt/app-root/src/packages/order-experience-api/
      - ./packages/order-experience-api/nodemon.json:/opt/app-root/src/packages/order-experience-api/nodemon.json
      - ./packages/order-backend/:/opt/app-root/src/packages/order-backend/
      - ./packages/cart-backend/:/opt/app-root/src/packages/cart-backend/
      - ./packages/core/:/opt/app-root/src/packages/core/
      - ./packages/product-backend/:/opt/app-root/src/packages/product-backend/
      - ./packages/price-backend/:/opt/app-root/src/packages/price-backend/
    container_name: order-experience-api
    expose:
      - '8080'
    ports:
      - '8084:8080'
    command: yarn workspace @verkkokauppa/order-experience-api dev
    environment:
      - SERVICE_NAME=order-experience-api
      - CART_BACKEND_URL=https://d526e9ec-74bf-4314-b708-f759a9d46958.mock.pstmn.io
      - PRICE_BACKEND_URL=https://3d615742-ed93-4415-8972-76c7103c5000.mock.pstmn.io
      - PRODUCT_BACKEND_URL=https://ff102df2-94c3-4243-a4a1-6e449f78c633.mock.pstmn.io
      - ORDER_BACKEND_URL=https://d04f2785-8b0b-4d0b-b52d-46c1878f6fa9.mock.pstmn.io
      - CHECKOUT_BASE_URL=https://checkout-test.dev.hel.fi