# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  paths:
    include:
    - packages/product-experience-api
  tags:
    include:
      - product-experience-api/*
  branches:
    include:
      - master

# Opting out of pull request validation
pr: none

resources:
  repositories:
    # Azure DevOps repository
    - repository: talpa-verkkokauppa-pipelines
      type: git
      # project/repository
      name: talpa-verkkokauppa/talpa-verkkokauppa-pipelines

extends:
  template: azure-pipelines-talpa-verkkokauppa-product-experience-api.yml@talpa-verkkokauppa-pipelines