openapi: 3.0.3
info:
  title: Merchant experience API
  version: 1.0.0
servers:
  - url: /v1/merchant
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      description: Api key for a namespace issued by talpa verkkokauppa
      in: header
      name: api-key
  schemas:
    ElasticSearchHealthResponse:
      type: object
      properties:
        body:
          type: object
          properties:
            cluster_name:
              type: string
            status:
              type: string
            timed_out:
              type: boolean
            number_of_nodes:
              type: integer
              format: int32
            number_of_data_nodes:
              type: integer
              format: int32
            active_primary_shards:
              type: integer
              format: int32
            active_shards:
              type: integer
              format: int32
            relocating_shards:
              type: integer
              format: int32
            initializing_shards:
              type: integer
              format: int32
            unassigned_shards:
              type: integer
              format: int32
            delayed_unassigned_shards:
              type: integer
              format: int32
            number_of_pending_tasks:
              type: integer
              format: int32
            number_of_in_flight_fetch:
              type: integer
              format: int32
            task_max_waiting_in_queue_millis:
              type: integer
              format: int32
            active_shards_percent_as_number:
              type: integer
              format: int32
        statusCode:
          type: integer
          format: int32
        headers:
          type: object
          properties:
            content-type:
              type: string
            content-length:
              type: string
        meta:
          type: object
          properties:
            context:
              type: string
              format: nullable
            request:
              type: object
              properties:
                params:
                  type: object
                  properties:
                    method:
                      type: string
                    path:
                      type: string
                    body:
                      type: string
                      format: nullable
                    querystring:
                      type: string
                    headers:
                      type: object
                      properties:
                        user-agent:
                          type: string
                        x-elastic-client-meta:
                          type: string
                    timeout:
                      type: integer
                      format: int32
                options:
                  type: object
                id:
                  type: integer
                  format: int32
            name:
              type: string
            connection:
              type: object
              properties:
                url:
                  type: string
                id:
                  type: string
                headers:
                  type: object
                deadCount:
                  type: integer
                  format: int32
                resurrectTimeout:
                  type: integer
                  format: int32
                _openRequests:
                  type: integer
                  format: int32
                status:
                  type: string
                roles:
                  type: object
                  properties:
                    master:
                      type: boolean
                    data:
                      type: boolean
                    ingest:
                      type: boolean
                    ml:
                      type: boolean
            attempts:
              type: integer
              format: int32
            aborted:
              type: boolean

    ErrorBody:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: string
              message:
                type: string

  responses:
    InvalidApiKey:
      description: Invalid api key
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
    RequestValidationFailed:
      description: Invalid request data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
paths:
  /health/elasticsearch:
    get:
      description: Get elasticsearch health response
      responses:
        '200':
          description: An object of merchant configurations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElasticSearchHealthResponse'

        '500':
          $ref: '#/components/responses/InternalServerError'